### ISSUE TITLE
Enable/Disable TX/RX via command line

### ISSUE THREAD

**Issue by 101jallen** [VE3NEA/OmniRig#9]
Hello, first thank you for your effort on OmniRig. I am looking for a way to simply "key the mic" via a cmd window.
For example keymic.exe rig1 on/off are there any utils out there to talk to omnirig via the cli?

**Comment by psabbag** [comment]
I wrote this script for AutoHotKey, it works with the middle button of the mouse and other keys I selected from my extended HP keyboard. In some cases there are a 300ms delay before release the PTT that I added to allow the audio buffer to empty, since I'm using a microphone connected with the PC as well.

#InstallKeybdHook

MButton::
	MyOmniRig := ComObjCreate("{0839E8C6-ED30-4950-8087-966F970F0CAE}")
	MyOmniRig.Rig1.Tx := 0x00400000
	ObjRelease(MyOmniRig)
return

MButton up::
	MyOmniRig := ComObjCreate("{0839E8C6-ED30-4950-8087-966F970F0CAE}")
	Sleep, 300
	MyOmniRig.Rig1.Tx := 0x00200000
	ObjRelease(MyOmniRig)
return

SC125::
	MyOmniRig := ComObjCreate("{0839E8C6-ED30-4950-8087-966F970F0CAE}")
	MyOmniRig.Rig1.Tx := 0x00400000
	ObjRelease(MyOmniRig)
return

SC125 up::
	MyOmniRig := ComObjCreate("{0839E8C6-ED30-4950-8087-966F970F0CAE}")
	Sleep, 300
	MyOmniRig.Rig1.Tx := 0x00200000
	ObjRelease(MyOmniRig)
return

SC126::
	MyOmniRig := ComObjCreate("{0839E8C6-ED30-4950-8087-966F970F0CAE}")
	MyOmniRig.Rig1.Tx := 0x00400000
	ObjRelease(MyOmniRig)
return

SC126 up::
	MyOmniRig := ComObjCreate("{0839E8C6-ED30-4950-8087-966F970F0CAE}")
	Sleep, 300
	MyOmniRig.Rig1.Tx := 0x00200000
	ObjRelease(MyOmniRig)
return

Launch_App2:: 
	MyOmniRig := ComObjCreate("{0839E8C6-ED30-4950-8087-966F970F0CAE}")
	MyOmniRig.Rig1.Tx := 0x00400000
	ObjRelease(MyOmniRig)
return

Launch_App2 up::
	MyOmniRig := ComObjCreate("{0839E8C6-ED30-4950-8087-966F970F0CAE}")
	Sleep, 300
	MyOmniRig.Rig1.Tx := 0x00200000
	ObjRelease(MyOmniRig)
return

73,
Pablo, VA3HDL

**Comment by 101jallen** [comment]
Excellent. I now have what I needed.
key.ahk > key.exe source
MyOmniRig := ComObjCreate("{0839E8C6-ED30-4950-8087-966F970F0CAE}")
MyOmniRig.Rig1.Tx := 0x00400000
ObjRelease(MyOmniRig)

unkey.ahk > unkey.exe source
MyOmniRig := ComObjCreate("{0839E8C6-ED30-4950-8087-966F970F0CAE}")
MyOmniRig.Rig1.Tx := 0x00200000
ObjRelease(MyOmniRig)

So I can key the mic, play the audio file and un key the mic all from within Voicemeeter Potato
